version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    labels:
      - "dependencies"
    groups:
      expo:
        patterns:
          - "expo"
          - "expo-*"
          - "@expo/*"
          - "@expo-google-fonts/*"
      react-native:
        patterns:
          - "react-native"
          - "react-native-*"
          - "@react-native-*/*"
      solana:
        patterns:
          - "@solana-mobile/*"
          - "@solana/*"
      lint-and-format:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
          - "prettier"
          - "prettier-*"
      types:
        patterns:
          - "@types/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
    labels:
      - "ci"
