// Cross-platform reproducibility gate.
//
// The mobile hashing layer (poseidon-lite backend) MUST produce byte-equal
// output to the web SDK (circomlibjs backend) for the same input. If this
// test ever goes red, the mobile fingerprint+commitment has diverged from
// every existing user's web baseline — DO NOT MERGE.
//
// Expected values were generated by running the web @entros/pulse-sdk@1.2.0
// against the deterministic fixture below. Regeneration command (run from
// `/Users/johnny/IAM/pulse-sdk/`):
//
//   node -e 'import("./dist/index.mjs").then(async (sdk) => {
//     const features = Array.from({length: 134}, (_, i) => Math.sin(i * 0.3) * Math.cos(i * 0.7));
//     const fp = sdk.simhash(features);
//     const salt = BigInt("12345678901234567890123456789012345678901234567890");
//     const commitment = await sdk.computeCommitment(fp, salt);
//     console.log({fp: fp.join(""), commitment, salt});
//   });'

import { bigintToBytes32, computeCommitment, generateTBH, packBits, simhash } from "../";

const FIXTURE_FEATURES = Array.from(
  { length: 134 },
  (_, i) => Math.sin(i * 0.3) * Math.cos(i * 0.7),
);

const EXPECTED_FINGERPRINT_BITS =
  "1111110000001011100110111100000110101000000111001111010101010111110101001111011000111101110110110110011011110010010100011100000110100101110010001111110111101111011010110101101111000011101000111001110011011110110000111001011000011010011000100010010110110001";

const EXPECTED_PACKBITS_LO = 174847014873938070697824370591050354751n;
const EXPECTED_PACKBITS_HI = 188274110863955655165565545772698506149n;

const FIXED_SALT = 12345678901234567890123456789012345678901234567890n;

const EXPECTED_COMMITMENT_BIGINT =
  10110574634330889523534359415537150161448473818199741808486987445477854994347n;
const EXPECTED_COMMITMENT_HEX = "165a61e834d97d2af9fa94e54a0aeefb12f4e003e12a7fd6d4fdafaa7c74dfab";

describe("hashing parity vs @entros/pulse-sdk@1.2.0", () => {
  test("simhash produces byte-identical 256-bit fingerprint", () => {
    const fp = simhash(FIXTURE_FEATURES);
    expect(fp).toHaveLength(256);
    expect(fp.join("")).toBe(EXPECTED_FINGERPRINT_BITS);
  });

  test("packBits splits fingerprint into the same lo/hi field elements", () => {
    const fp = simhash(FIXTURE_FEATURES);
    const { lo, hi } = packBits(fp);
    expect(lo).toBe(EXPECTED_PACKBITS_LO);
    expect(hi).toBe(EXPECTED_PACKBITS_HI);
  });

  test("computeCommitment produces the same Poseidon output for fixed salt", async () => {
    const fp = simhash(FIXTURE_FEATURES);
    const commitment = await computeCommitment(fp, FIXED_SALT);
    expect(commitment).toBe(EXPECTED_COMMITMENT_BIGINT);
  });

  test("bigintToBytes32 yields the expected 32-byte big-endian representation", async () => {
    const fp = simhash(FIXTURE_FEATURES);
    const commitment = await computeCommitment(fp, FIXED_SALT);
    const bytes = bigintToBytes32(commitment);
    expect(bytes).toHaveLength(32);
    const hex = Array.from(bytes)
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("");
    expect(hex).toBe(EXPECTED_COMMITMENT_HEX);
  });

  test("generateTBH returns the same commitment when salt is supplied", async () => {
    const fp = simhash(FIXTURE_FEATURES);
    const tbh = await generateTBH(fp, FIXED_SALT);
    expect(tbh.commitment).toBe(EXPECTED_COMMITMENT_BIGINT);
    expect(tbh.salt).toBe(FIXED_SALT);
    const hex = Array.from(tbh.commitmentBytes)
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("");
    expect(hex).toBe(EXPECTED_COMMITMENT_HEX);
  });

  test("generateTBH with random salt still produces a valid 32-byte commitment", async () => {
    const fp = simhash(FIXTURE_FEATURES);
    const tbh = await generateTBH(fp);
    expect(typeof tbh.salt).toBe("bigint");
    expect(typeof tbh.commitment).toBe("bigint");
    expect(tbh.commitmentBytes).toHaveLength(32);
    // Random-salt round trip: bytes ↔ bigint must be lossless.
    const reconstructed = Array.from(tbh.commitmentBytes).reduce(
      (acc, b) => (acc << 8n) + BigInt(b),
      0n,
    );
    expect(reconstructed).toBe(tbh.commitment);
  });
});
